services:
  # tavern:
  #   image: alexzvn/spigot-runner:eta
  #   tty: true
  #   stdin_open: true
  #   restart: always
  #   ports:
  #     - 25599:25565
  #   environment:
  #     VERSION: 1.20.1
  #     GB_MEMORY: 8
  #   volumes:
  #     - ./taverncraft:/server
  #   networks:
  #     - database-net
  # new-tavern:
  #   image: alexzvn/spigot-runner:eta
  #   tty: true
  #   stdin_open: true
  #   restart: always
  #   ports:
  #     - 25598:25565
  #   environment:
  #     VERSION: 1.20.1
  #     GB_MEMORY: 8
  #     JAR_NAME: paper-1.20.6-151.jar
  #   volumes:
  #     - ./new-tavern:/server
  #   networks:
  #     - database-net

  taverncraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 25570:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.20.6"
      MEMORY: "6000M"
      ONLINE_MODE: "false"
      USE_AIKAR_FLAGS: "true"
      TZ: "Asia/Bangkok"
    volumes:
      - ./taverncraft1.20.6:/data
  taverntest:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 25575:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.20.6"
      MEMORY: "6000M"
      ONLINE_MODE: "false"
      USE_AIKAR_FLAGS: "true"
      TZ: "Asia/Bangkok"
    volumes:
      - ./taverntest2:/data
# Generated by setupmc.com on 2025-12-01T11:33:37.859Z

  tavernmon:
    image: itzg/minecraft-server:java21
    tty: true
    stdin_open: true
    ports:
      - "25571:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21.1"
      FABRIC_LOADER_VERSION: "0.18.4"
      MEMORY: "10000M"
      MAX_PLAYERS: "50"
      MOTD: "TavernMon"
    volumes:
      - "./tavernmon:/data"


  bungee:
    image: itzg/mc-proxy
    restart: always
    volumes:
      - ./bungee:/server
    ports:
      - 25569:25565
    stdin_open: true
    tty: true
    environment:
      - TYPE=VELOCITY
      - MEMORY=2048m
    networks:
      - database-net

  coreteam-app:
    build: ./coreteam-hr # Thư mục chứa code HR (Dockerfile, server.js, index.html,...)
    container_name: coreteam-hr
    restart: always
    ports:
      - "25572:3000" # Map cổng 25572 của VPS vào 3000 của container
    volumes:
      # Map file tĩnh để không xịt data nếu có restart docker
      - ./coreteam-hr/data.json:/usr/src/app/data.json

networks:
  database-net:
    driver: bridge
